services:
  frontend:
    build: ./frontend
    ports:
      - "8020:8020"
    depends_on:
      - api
    networks:
      - mynetwork
    environment:
      - PORT=8020
      - VITE_API_URL=http://api:8030
    image: "paulcoulm/map-tracing:latest"

  api:
    build: ./backend/api
    ports:
      - "8030:8030"
    depends_on:
      - soapservice
    networks:
      - mynetwork
    environment:
      - PORT=8030
      - SOAP_API_URL=http://soapservice:8033
    image: "paulcoulm/map-tracing:latest"

  soapservice:
    build: ./backend/serviceSoap
    ports:
      - "8033:8033"
    networks:
      - mynetwork
    environment:
      - PORT=8033
    image: "paulcoulm/map-tracing:latest"

networks:
  mynetwork:
    driver: bridge
