services:
  frontend:
    build: ./frontend
    ports:
      - "8020:8020"
    depends_on:
      - api
    networks:
      - mynetwork
    environment:
      - PORT=8020
    image: "paulcoulm/borneelectrictp:latest"

  api:
    build: ./backend/api
    ports:
      - "8030:8030"
    depends_on:
      - soapservice
    networks:
      - mynetwork
    environment:
      - PORT=8030
    image: "paulcoulm/borneelectrictp:latest"

  soapservice:
    build: ./backend/serviceSoap
    ports:
      - "8033:8033"
    networks:
      - mynetwork
    environment:
      - PORT=8033
    image: "paulcoulm/borneelectrictp:latest"

networks:
  mynetwork:
    driver: bridge
